<?xml version="1.0" encoding="utf-8"?><Database Name="Demo Database NAV (10-0)" Class="Nav_DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=KRUEGERM-NB\NAV90SQL;Initial Catalog=&quot;Demo Database NAV (10-0)&quot;;Integrated Security=True;Connect Timeout=60;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="Nav_API.Properties.Settings" SettingsPropertyName="Demo_Database_NAV__10_0_ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Object" Member="Object">
    <Type Name="Object">
      <Column Name="timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Company Name]" Member="Company_Name" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Compiled" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="[BLOB Reference]" Member="BLOB_Reference" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="[BLOB Size]" Member="BLOB_Size" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[DBM Table No_]" Member="DBM_Table_No_" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Version List]" Member="Version_List" Type="System.String" DbType="VarChar(248) NOT NULL" CanBeNull="false" />
      <Column Name="Locked" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="[Locked By]" Member="Locked_By" Type="System.String" DbType="VarChar(132) NOT NULL" CanBeNull="false" />
      <Association Name="Object_Object_Metadata" Member="Object_Metadata" ThisKey="Type,ID" OtherKey="Object_Type,Object_ID" Type="Object_Metadata" />
      <Association Name="Object_Object_Options" Member="Object_Options" ThisKey="ID,Type" OtherKey="Object_ID,Object_Type" Type="Object_Options" />
      <Association Name="Object_Object_Tracking" Member="Object_Tracking" ThisKey="Type,ID" OtherKey="Object_Type,Object_ID" Type="Object_Tracking" />
      <Association Name="Object_Object_Translation" Member="Object_Translation" ThisKey="Type,ID" OtherKey="Object_Type,Object_ID" Type="Object_Translation" />
      <Association Name="Company_Object" Member="Company" ThisKey="Company_Name" OtherKey="Name" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Object Metadata]" Member="Object_Metadata">
    <Type Name="Object_Metadata">
      <Column Name="timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="[Object Type]" Member="Object_Type" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Object ID]" Member="Object_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Metadata" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="[User Code]" Member="User_Code" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="[User AL Code]" Member="User_AL_Code" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="[Metadata Version]" Member="Metadata_Version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Hash" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="[Object Subtype]" Member="Object_Subtype" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="[Has Subscribers]" Member="Has_Subscribers" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Object_Metadata_Object_Metadata_Snapshot" Member="Object_Metadata_Snapshot" ThisKey="Object_Type,Object_ID" OtherKey="Object_Type,Object_ID" Type="Object_Metadata_Snapshot" />
      <Association Name="Object_Object_Metadata" Member="Object" ThisKey="Object_Type,Object_ID" OtherKey="Type,ID" Type="Object" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Object Metadata Snapshot]" Member="Object_Metadata_Snapshot">
    <Type Name="Object_Metadata_Snapshot">
      <Column Name="timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="[Object Type]" Member="Object_Type" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Object ID]" Member="Object_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Metadata" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="[Data Per Company]" Member="Data_Per_Company" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Hash" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="[Base Metadata]" Member="Base_Metadata" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="[Base Hash]" Member="Base_Hash" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Association Name="Object_Metadata_Object_Metadata_Snapshot" Member="Object_Metadata" ThisKey="Object_Type,Object_ID" OtherKey="Object_Type,Object_ID" Type="Object_Metadata" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Object Options]" Member="Object_Options">
    <Type Name="Object_Options">
      <Column Name="timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="[Parameter Name]" Member="Parameter_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Object ID]" Member="Object_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Object Type]" Member="Object_Type" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Company Name]" Member="Company_Name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="[User Name]" Member="User_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Option Data]" Member="Option_Data" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="[Public Visible]" Member="Public_Visible" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Temporary" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Object_Object_Options" Member="Object" ThisKey="Object_ID,Object_Type" OtherKey="ID,Type" Type="Object" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Object Tracking]" Member="Object_Tracking">
    <Type Name="Object_Tracking">
      <Column Name="timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="[Object Type]" Member="Object_Type" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Object ID]" Member="Object_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Change Type]" Member="Change_Type" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[App Package ID]" Member="App_Package_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Tenant ID]" Member="Tenant_ID" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Object Timestamp]" Member="Object_Timestamp" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Object_Object_Tracking" Member="Object" ThisKey="Object_Type,Object_ID" OtherKey="Type,ID" Type="Object" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Object Translation]" Member="Object_Translation">
    <Type Name="Object_Translation">
      <Column Name="timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="[Object Type]" Member="Object_Type" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Object ID]" Member="Object_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Language ID]" Member="Language_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="Object_Object_Translation" Member="Object" ThisKey="Object_Type,Object_ID" OtherKey="Type,ID" Type="Object" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Company" Member="Company">
    <Type Name="Company">
      <Column Name="timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Company_Object" Member="Object" ThisKey="Name" OtherKey="Company_Name" Type="Object" />
    </Type>
  </Table>
  <Table Name="dbo.[AL BackUp]" Member="AL_BackUp">
    <Type Name="AL_BackUp">
      <Column Name="Type" Type="System.Int32" DbType="int not null" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="[Company Name]" Member="Company_Name" Type="System.String" DbType="varchar(30) not null" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ID" Type="System.Int32" DbType="int not null" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="[AL Code]" Member="AL_Code" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[AL Code Size]" Member="AL_Code_Size" Type="System.Int32" DbType="int not null" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Code" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[User Code]" Member="User_Code" Type="System.Data.Linq.Binary" DbType="image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>